version: 2

sources:
  - name: snowflake_sample_src
    description: this is a replica of the snowflake database sample
    database: snowflake_sample_data
    schema: tpcds_sf10tcl
#    freshness: # default freshness for all tables in this source
#      warn_after: {count: 5, period: hour}
#      error_after: {count: 12, period: hour}
#      loaded_at_field: "convert_timezone('America/Los_Angeles', 'UTC', created_at)"
#      filter: datediff('hour', loaded_at, current_timestamp()) < 1

    tables:
      - name: store_sales
        description: one record per customer.
        columns:
          - name: ss_sold_date_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_sold_time_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
            meta:
              masking_policy: mp_encrypt_pii
          - name: ss_item_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_customer_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_cdemo_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_hdemo_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_addr_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_store_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_promo_sk
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_ticket_number
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_quantity
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_wholesale_cost
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_list_price
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_sales_price
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_ext_discount_amt
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
          - name: ss_ext_sales_price
            description: "The primary key for this table"
