version: 2

sources:
  - name: snowflake_sample_src
    description: this is a replica of the snowflake database sample
    database: snowflake_sample_data
    schema: tpcds_sf10tcl
#    freshness: # default freshness for all tables in this source
#      warn_after: {count: 5, period: hour}
#      error_after: {count: 12, period: hour}
#      loaded_at_field: "convert_timezone('America/Los_Angeles', 'UTC', created_at)"
#      filter: datediff('hour', loaded_at, current_timestamp()) < 1

    tables:
      - name: store_sales
        description: one record per customer.